// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnOT5vBFopKzEYIhUVVVmLte2HGKwPyok',
    appId: '1:189429643486:web:7ccf68def72861f2346a4f',
    messagingSenderId: '189429643486',
    projectId: 'test-dacn-123',
    authDomain: 'test-dacn-123.firebaseapp.com',
    storageBucket: 'test-dacn-123.appspot.com',
    measurementId: 'G-TWD9SGRWGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHHWWSGyIDsogy8guE7OR2zD74Th0rtgw',
    appId: '1:189429643486:android:0988ea946e892667346a4f',
    messagingSenderId: '189429643486',
    projectId: 'test-dacn-123',
    storageBucket: 'test-dacn-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQbIImXx34U5jHMjYIc_HsCtG1AhlEZj8',
    appId: '1:189429643486:ios:7b157b4ce8c40a31346a4f',
    messagingSenderId: '189429643486',
    projectId: 'test-dacn-123',
    storageBucket: 'test-dacn-123.appspot.com',
    iosBundleId: 'com.example.dacn2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQbIImXx34U5jHMjYIc_HsCtG1AhlEZj8',
    appId: '1:189429643486:ios:7b157b4ce8c40a31346a4f',
    messagingSenderId: '189429643486',
    projectId: 'test-dacn-123',
    storageBucket: 'test-dacn-123.appspot.com',
    iosBundleId: 'com.example.dacn2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnOT5vBFopKzEYIhUVVVmLte2HGKwPyok',
    appId: '1:189429643486:web:5beda438da1894f8346a4f',
    messagingSenderId: '189429643486',
    projectId: 'test-dacn-123',
    authDomain: 'test-dacn-123.firebaseapp.com',
    storageBucket: 'test-dacn-123.appspot.com',
    measurementId: 'G-9DW7VXMGWN',
  );
}
